### ISSUE TITLE
Fresh install doesn't create the tomcat/temp directory

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#109]
Fresh install on Ubuntu does not create the tomcat/temp directory and Proteus won't work on start b/c of this:

```
INFO: Cloning Git / SVN project: [oodt] remote repo: [https://github.com/apache/oodt.git] into /home/mattmann/drat/deploy/tomcat/temp
java.io.IOException: /home/mattmann/drat/deploy/tomcat/temp doesn't exist.
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:163)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at drat.proteus.DratStartForm.parseAsVersionControlledRepo(DratStartForm.java:207)
	at drat.proteus.DratStartForm.handleSubmit(DratStartForm.java:127)
	at drat.proteus.DratStartForm.onSubmit(DratStartForm.java:88)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1313)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:976)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:797)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:708)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:241)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:234)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ThejanW** [comment]
@chrismattmann can't we just give a bash script to automatically set the environment vars & install it. Similar to solr. Please see https://github.com/apache/lucene-solr/blob/master/solr/bin/install_solr_service.sh

**Comment by chrismattmann** [comment]
yea @ThejanW i think there is an even simpler fix here. We just need to update the assembly.xml to create that directory and include a REMOVE.log file in there.

**Comment by anutin544** [comment]
Ok

**Comment by buggtb** [comment]
I've been deploying on ubuntu and mac osx for a week and haven't seen this so I think we can close this one down.
