### ISSUE TITLE
PGE failure

### ISSUE THREAD

**Issue by buggtb** [apache/drat#139]
So i'm running it now and its working in terms of the Crawl via proteus. 

What I do see in the logs though is 

```
SEVERE: PGETask FAILED!!! : Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
java.io.IOException: Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
	at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:68)
	at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:217)
	at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:109)
	at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.executeTaskLocally(IterativeWorkflowProcessorThread.java:573)
	at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:324)
	at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.oodt.cas.pge.exceptions.PGEException: Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
	at org.apache.oodt.cas.pge.util.XmlHelper.fillIn(XmlHelper.java:461)
	at org.apache.oodt.cas.pge.util.XmlHelper.fillIn(XmlHelper.java:439)
	at org.apache.oodt.cas.pge.util.XmlHelper.getMetadataValues(XmlHelper.java:204)
	at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.loadCustomMetadata(XmlFilePgeConfigBuilder.java:146)
	at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.loadConfigFile(XmlFilePgeConfigBuilder.java:101)
	at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:64)
	... 6 more
Caused by: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: org.apache.xmlrpc.XmlRpcException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.complexQuery(XmlRpcFileManagerClient.java:997)
	at org.apache.oodt.cas.pge.util.XmlHelper.fillIn(XmlHelper.java:456)
	... 11 more
Caused by: org.apache.xmlrpc.XmlRpcException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
	at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeException(XmlRpcClientResponseProcessor.java:104)
	at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeResponse(XmlRpcClientResponseProcessor.java:71)
	at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:73)
	at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
	at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
	at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178)
	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.complexQuery(XmlRpcFileManagerClient.java:992)
	... 12 more
```
Looking at it in a debugger its because 

https://github.com/apache/oodt/blob/release-1.2.2/filemgr/src/main/java/org/apache/oodt/cas/filemgr/system/XmlRpcFileManager.java#L1431-L1440

returns null and the query is empty, it seems. But I can trace that same method back to OODT 1.0 and before and its not changed, so has DRAT always reported this, or is this something new?

**Comment by buggtb** [comment]
Okay tested against 1.1 and don't see it, so I guess its an OODT regression... debugging.

**Comment by chrismattmann** [comment]
This looks like the RatAggregator Task is getting fired off before there are any RatLogs. You can check this in your Opsui FM browser. What do you see when you get this error?

**Comment by buggtb** [comment]
checking, I'll let you know shortly.

**Comment by buggtb** [comment]
Trying to figure out some of the wiring. The Lucene bug was from OODT using the lucene catalog, but there's a solr server and the mimepartitioner seems to query it? But its empty when I run it.

**Comment by chrismattmann** [comment]
hmmm that suggests that the indexing process either didn't run or failed. After crawling, it has to run the Solr indexer, to ingest the CAS FM metadata into Solr. It runs SolrDumper. This should be present inside of the Proteus logs, do you see it there?  @buggtb

**Comment by buggtb** [comment]
Alright, as i mentioned in the slack channel I think this is a non issue and is infact cause by the docs being a bit stale and missing the alias stuff as I've stuck it in and its now been indexing for 30 minutes. Have to shut it off and catch a flight but I think if you test the OODT PR from yesterday this issue will likely go away.

**Comment by buggtb** [comment]
Okay after a myriad of env vars getting set, I think this is a non bug.
