### ISSUE TITLE
Proteus doesn't index

### ISSUE THREAD

**Issue by buggtb** [apache/drat#141]
Not yet sure whats going on. 

Proteus crawls fine, then gets to teh index phase and blocks up. If you index manually then run the map and reduce phase in Proteus its fine. So something has changed in the index process to make it sad.

**Comment by buggtb** [comment]
Ah found this in the proteus logs:

SEVERE: Could not connect to Solr server null
java.lang.InstantiationException: no protocol: null
        at org.apache.oodt.cas.filemgr.tools.SolrIndexer.<init>(SolrIndexer.java:141)
        at backend.ProcessDratWrapper.solrIndex(ProcessDratWrapper.java:154)
        at backend.ProcessDratWrapper.index(ProcessDratWrapper.java:146)
        at backend.ProcessDratWrapper.go(ProcessDratWrapper.java:256)
        at drat.proteus.DratRunnable.run(DratRunnable.java:44)
        at java.lang.Thread.run(Thread.java:748)

**Comment by buggtb** [comment]
Boom I was missing yet another env var. 
export SOLR_DRAT_URL=http://localhost:8080/solr/drat
