### ISSUE TITLE
java.lang.RuntimeException: Pge didn't finish successfully

### ISSUE THREAD

**Issue by lewismc** [apache/drat#39]
I am getting a runtime exception and subsequent failure of the entire **go** task using master branch as of today.
@jihyunoh can you please review and see if it is/was the same or similar issue to that you were getting a few weeks ago...

```
INFO: Loading PgeConfig file '/usr/local/drat/deploy//pge/policy/PgeConfig_MimePartitioner.xml'
Jun 02, 2015 10:44:30 AM org.apache.oodt.cas.pge.PGETaskInstance createExeDir
INFO: Creating PGE execution working directory: [/usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660]
Jun 02, 2015 10:44:30 AM org.apache.oodt.cas.pge.PGETaskInstance updateStatus
INFO: Updating status to workflow as BUILDING CONFIG FILE
Jun 02, 2015 10:44:30 AM org.apache.oodt.cas.pge.PGETaskInstance updateStatus
INFO: Updating status to workflow as PGE EXEC
Jun 02, 2015 10:44:30 AM org.apache.oodt.commons.io.LoggerOutputStream flush
INFO: OUTPUT: Creating working dirs
OUTPUT: Running MIME partitioner

Jun 02, 2015 10:44:30 AM org.apache.oodt.commons.io.LoggerOutputStream flush
SEVERE: ERROR:   File "/usr/local/drat/deploy//pge/bin/mime_partitioner/mime_rat_partitioner.py", line 111
ERROR: SyntaxError: Non-ASCII character '\xe2' in file /usr/local/drat/deploy//pge/bin/mime_partitioner/mime_rat_partitioner.py on line 111, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Jun 02, 2015 10:44:30 AM org.apache.oodt.commons.io.LoggerOutputStream flush
INFO: OUTPUT: Creating working dirs
OUTPUT: Running MIME partitioner

java.lang.RuntimeException: Pge didn't finish successfully
    at org.apache.oodt.cas.pge.PGETaskInstance.runPge(PGETaskInstance.java:322)
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:451)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.executeTaskLocally(IterativeWorkflowProcessorThread.java:574)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:321)
    at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
org.apache.oodt.cas.workflow.structs.exceptions.WorkflowTaskInstanceException: PGETask failed : Exception when executing PGE commands '[export PATH=$HOME/bin/:${PATH}, shopt -s expand_aliases, echo "Creating working dirs", mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/input ; mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/output; mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/logs, echo "Running MIME partitioner", /usr/local/drat/deploy//pge/bin/mime_partitioner/mime_rat_partitioner.py -u http://localhost:8080/solr/drat -c 100 -w http://localhost:9001 -t urn:drat:RatCodeAudit > /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/logs/mime-partitioner-1433267070660.log]' : Pge didn't finish successfully
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:456)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.executeTaskLocally(IterativeWorkflowProcessorThread.java:574)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:321)
    at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Exception when executing PGE commands '[export PATH=$HOME/bin/:${PATH}, shopt -s expand_aliases, echo "Creating working dirs", mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/input ; mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/output; mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/logs, echo "Running MIME partitioner", /usr/local/drat/deploy//pge/bin/mime_partitioner/mime_rat_partitioner.py -u http://localhost:8080/solr/drat -c 100 -w http://localhost:9001 -t urn:drat:RatCodeAudit > /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/logs/mime-partitioner-1433267070660.log]' : Pge didn't finish successfully
    at org.apache.oodt.cas.pge.PGETaskInstance.runPge(PGETaskInstance.java:334)
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:451)
    ... 4 more
Jun 02, 2015 10:44:30 AM org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread executeTaskLocally
WARNING: Exception executing task: [MimePartitioner] locally: Message: PGETask failed : Exception when executing PGE commands '[export PATH=$HOME/bin/:${PATH}, shopt -s expand_aliases, echo "Creating working dirs", mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/input ; mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/output; mkdir /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/logs, echo "Running MIME partitioner", /usr/local/drat/deploy//pge/bin/mime_partitioner/mime_rat_partitioner.py -u http://localhost:8080/solr/drat -c 100 -w http://localhost:9001 -t urn:drat:RatCodeAudit > /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660/logs/mime-partitioner-1433267070660.log]' : Pge didn't finish successfully
Jun 02, 2015 10:44:36 AM org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread checkTaskRequiredMetadata
INFO: Task: [RatAggregator] has no required metadata fields
Jun 02, 2015 10:44:36 AM org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread executeTaskLocally
INFO: Executing task: [RatAggregator] locally
Jun 02, 2015 10:44:36 AM org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder buildImports
INFO: Loading PgeConfig file '/usr/local/drat/deploy//pge/policy/PgeConfig_RatAggregator.xml'
Jun 02, 2015 10:44:37 AM org.apache.oodt.cas.filemgr.catalog.LuceneCatalog paginateQuery
WARNING: Query: [q=] for Product Type: [urn:drat:RatLog] returned no results
java.lang.NullPointerException
    at org.apache.oodt.cas.filemgr.system.XmlRpcFileManager.complexQuery(XmlRpcFileManager.java:607)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.xmlrpc.Invoker.execute(Invoker.java:130)
    at org.apache.xmlrpc.XmlRpcWorker.invokeHandler(XmlRpcWorker.java:84)
    at org.apache.xmlrpc.XmlRpcWorker.execute(XmlRpcWorker.java:146)
    at org.apache.xmlrpc.XmlRpcServer.execute(XmlRpcServer.java:139)
    at org.apache.xmlrpc.XmlRpcServer.execute(XmlRpcServer.java:125)
    at org.apache.xmlrpc.WebServer$Connection.run(WebServer.java:761)
    at org.apache.xmlrpc.WebServer$Runner.run(WebServer.java:642)
    at java.lang.Thread.run(Thread.java:745)
org.apache.xmlrpc.XmlRpcException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
    at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeException(XmlRpcClientResponseProcessor.java:104)
    at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeResponse(XmlRpcClientResponseProcessor.java:71)
    at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:73)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178)
    at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.complexQuery(XmlRpcFileManagerClient.java:1003)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:322)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:313)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.getCustomMetadata(XmlFilePgeConfigBuilder.java:180)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:109)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.buildImports(XmlFilePgeConfigBuilder.java:101)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:69)
    at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:133)
    at org.apache.oodt.cas.pge.PGETaskInstance.initialize(PGETaskInstance.java:98)
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:449)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.executeTaskLocally(IterativeWorkflowProcessorThread.java:574)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:321)
    at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:326)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:313)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.getCustomMetadata(XmlFilePgeConfigBuilder.java:180)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:109)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.buildImports(XmlFilePgeConfigBuilder.java:101)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:69)
    at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:133)
    at org.apache.oodt.cas.pge.PGETaskInstance.initialize(PGETaskInstance.java:98)
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:449)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.executeTaskLocally(IterativeWorkflowProcessorThread.java:574)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:321)
    at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
    at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.complexQuery(XmlRpcFileManagerClient.java:1009)
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:322)
    ... 12 more
java.io.IOException: Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
    at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:75)
    at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:133)
    at org.apache.oodt.cas.pge.PGETaskInstance.initialize(PGETaskInstance.java:98)
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:449)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.executeTaskLocally(IterativeWorkflowProcessorThread.java:574)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:321)
    at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
org.apache.oodt.cas.workflow.structs.exceptions.WorkflowTaskInstanceException: PGETask failed : Failed to instanciate PGETaskInstance : Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:456)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.executeTaskLocally(IterativeWorkflowProcessorThread.java:574)
    at org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread.run(IterativeWorkflowProcessorThread.java:321)
    at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InstantiationException: Failed to instanciate PGETaskInstance : Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
    at org.apache.oodt.cas.pge.PGETaskInstance.initialize(PGETaskInstance.java:116)
    at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:449)
    ... 4 more
Jun 02, 2015 10:44:37 AM org.apache.oodt.cas.workflow.engine.IterativeWorkflowProcessorThread executeTaskLocally
WARNING: Exception executing task: [RatAggregator] locally: Message: PGETask failed : Failed to instanciate PGETaskInstance : Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
Jun 02, 2015 10:45:25 AM org.apache.oodt.cas.filemgr.catalog.LuceneCatalog paginateQuery
WARNING: Query: [q=] for Product Type: [urn:drat:RatAggregateLog] returned no results
```

**Comment by chrismattmann** [comment]
@lewismc what happens if you:

```
cd /usr/local/drat/deploy//data/jobs/mimepartitioner/1433267070660 && sh *.sh
```

?

**Comment by jihyunoh** [comment]
@lewismc Unfortunately, I reinstalled DRAT, so I don't keep the previous log file... But if DRAT runs successfully, it shows this message:

May 27, 2015 1:01:12 PM org.apache.oodt.commons.io.LoggerOutputStream flush
INFO: OUTPUT: Creating working dirs
OUTPUT: Running MIME partitioner

May 27, 2015 1:01:12 PM org.apache.oodt.cas.pge.PGETaskInstance runPge
INFO: Successfully completed running: '[export PATH=$HOME/bin/:${PATH}, shopt -s expand_aliases, echo "Creating working dirs", mkdir /Users/ohjihyun/drat/deploy/data/jobs/mimepartitioner/1432746072346/input ; mkdir /Users/ohjihyun/drat/deploy/data/jobs/mimepartitioner/1432746072346/output; mkdir /Users/ohjihyun/drat/deploy/data/jobs/mimepartitioner/1432746072346/logs, echo "Running MIME partitioner", /Users/ohjihyun/drat/deploy/pge/bin/mime_partitioner/mime_rat_partitioner.py -u http://localhost:8080/solr/drat -c 100 -w http://localhost:9001 -t urn:drat:RatCodeAudit > /Users/ohjihyun/drat/deploy/data/jobs/mimepartitioner/1432746072346/logs/mime-partitioner-1432746072346.log]'
May 27, 2015 1:01:12 PM org.apache.oodt.cas.pge.PGETaskInstance setCrawlerConfigurations
INFO: Passing Workflow Metadata to CAS-Crawler as global metadata . . .

**Comment by jihyunoh** [comment]
@lewismc But is it normal to have '//' for the path? 
Ex) your path:  '/usr/local/drat/deploy"//"pge/policy/PgeConfig_MimePartitioner.xml

**Comment by chrismattmann** [comment]
@lewismc the issue here seems to be:

```
SEVERE: ERROR:   File "/usr/local/drat/deploy//pge/bin/mime_partitioner/mime_rat_partitioner.py", line 111
ERROR: SyntaxError: Non-ASCII character '\xe2' in file /usr/local/drat/deploy//pge/bin/mime_partitioner/mime_rat_partitioner.py on line 111, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

What code base did you try this on?

**Comment by lewismc** [comment]
@chrismattmann in all honesty it is a bad bug report from me. I cannot reproduce this sorry!

**Comment by chrismattmann** [comment]
Thanks Lewis
