### ISSUE TITLE
org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null

### ISSUE THREAD

**Issue by karanjeets** [apache/drat#53]
Hello,

I am getting the below error while running DRAT using resource manager. Is there any known solution for this ?

Note - The resource manager was earlier looking for cas-filemgr-0.10.jar. I added that and the error shifted to the below one.

```
INFO: Loading PgeConfig file '/root/drat/deploy/pge/policy/PgeConfig_RatAggregator.xml'
org.apache.xmlrpc.XmlRpcException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
        at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeException(XmlRpcClientResponseProcessor.java:104)
        at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeResponse(XmlRpcClientResponseProcessor.java:71)
        at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:73)
        at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
        at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
        at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178)
        at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.complexQuery(XmlRpcFileManagerClient.java:1003)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:322)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:313)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.getCustomMetadata(XmlFilePgeConfigBuilder.java:180)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:109)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.buildImports(XmlFilePgeConfigBuilder.java:101)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:69)
        at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:133)
        at org.apache.oodt.cas.pge.PGETaskInstance.initialize(PGETaskInstance.java:98)
        at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:449)
        at org.apache.oodt.cas.workflow.structs.TaskJob.execute(TaskJob.java:102)
        at org.apache.oodt.cas.resource.system.extern.XmlRpcBatchStub$RunnableJob.run(XmlRpcBatchStub.java:229)
        at java.lang.Thread.run(Thread.java:745)
java.lang.Exception: Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:326)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:313)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.getCustomMetadata(XmlFilePgeConfigBuilder.java:180)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:109)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.buildImports(XmlFilePgeConfigBuilder.java:101)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:69)
        at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:133)
        at org.apache.oodt.cas.pge.PGETaskInstance.initialize(PGETaskInstance.java:98)
        at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:449)
        at org.apache.oodt.cas.workflow.structs.TaskJob.execute(TaskJob.java:102)
        at org.apache.oodt.cas.resource.system.extern.XmlRpcBatchStub$RunnableJob.run(XmlRpcBatchStub.java:229)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: java.lang.Exception: org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: Failed to perform complex query : null
        at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.complexQuery(XmlRpcFileManagerClient.java:1009)
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.fillIn(XmlFilePgeConfigBuilder.java:322)
        ... 11 more
java.io.IOException: Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
        at org.apache.oodt.cas.pge.config.XmlFilePgeConfigBuilder.build(XmlFilePgeConfigBuilder.java:75)
        at org.apache.oodt.cas.pge.PGETaskInstance.createPgeConfig(PGETaskInstance.java:133)
        at org.apache.oodt.cas.pge.PGETaskInstance.initialize(PGETaskInstance.java:98)
        at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:449)
        at org.apache.oodt.cas.workflow.structs.TaskJob.execute(TaskJob.java:102)
        at org.apache.oodt.cas.resource.system.extern.XmlRpcBatchStub$RunnableJob.run(XmlRpcBatchStub.java:229)
        at java.lang.Thread.run(Thread.java:745)
org.apache.oodt.cas.resource.structs.exceptions.JobInputException: Failed to run task
        at org.apache.oodt.cas.workflow.structs.TaskJob.execute(TaskJob.java:104)
        at org.apache.oodt.cas.resource.system.extern.XmlRpcBatchStub$RunnableJob.run(XmlRpcBatchStub.java:229)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.oodt.cas.workflow.structs.exceptions.WorkflowTaskInstanceException: PGETask failed : Failed to instanciate PGETaskInstance : Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
        at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:456)
        at org.apache.oodt.cas.workflow.structs.TaskJob.execute(TaskJob.java:102)
        ... 2 more
Caused by: java.lang.InstantiationException: Failed to instanciate PGETaskInstance : Failed to build PgeConfig : Failed to parse value: SQL(FORMAT='$FileLocation/$Filename',SORT_BY='CAS.ProductReceivedTime'){SELECT FileLocation,Filename,CAS.ProductReceivedTime FROM RatLog}
        at org.apache.oodt.cas.pge.PGETaskInstance.initialize(PGETaskInstance.java:116)
        at org.apache.oodt.cas.pge.PGETaskInstance.run(PGETaskInstance.java:449)
        ... 3 more
Oct 16, 2015 8:10:35 PM org.apache.oodt.cas.resource.system.extern.XmlRpcBatchStub genericExecuteJob
INFO: stub attempting to execute class: [org.apache.oodt.cas.workflow.structs.TaskJob]
```

**Comment by karanjeets** [comment]
I am somehow able to find the cause, which is because of non-sequential ordering of tasks. It seems to be an intermittent error where RatAggregator is running before RatCodeAudit.

Is there a way to control the job order while running DRAT using resource manager ?

**Comment by karanjeets** [comment]
I am quite close to the problem now. The reason it shoots an error is because we are sending jobs to resource manager for scheduling and execution and thus DRAT's function `current_pges` to check for running PGEs fails. We need something to monitor jobs submitted to resource manager and once it's finished, we execute our reducer (RatAggregator).

I was reading about [Ganglia plugin](https://cwiki.apache.org/confluence/display/OODT/Ganglia+plugin+for+CAS+Resource+Manager) but not sure how can I integrate it with DRAT to monitor jobs via shell script. Need Help.

**Comment by chrismattmann** [comment]
got it. I will take a look here @karanjeets - we can easily do this as a workflow with a condition.

**Comment by lewismc** [comment]
> It seems to be an intermittent error where RatAggregator is running before RatCodeAudit.

Is this truly intermittent? How can I reproduce it?

**Comment by karanjeets** [comment]
@lewismc Please follow the below steps to reproduce it.
1. Edit `DRAT_HOME/workflow/etc/workflow.properties` and uncomment the line 36 to send workflow jobs to resource manager. Change the port number to 9002.
2. Run `DRAT_HOME/resmgr/bin/batch_stub` on port 2001.
3. Optional - Edit `logging.properties` to verbose errors.
4. Run DRAT 2 - 3 times on a small code repository to test.

**Comment by karanjeets** [comment]
@chrismattmann @lewismc 
For this one, I am not sure on which file we can put workflow condition. If we are talking about `${DRAT_HOME}/data/archive/rat/<rat_mimetype_folder>/rat_*.log`, the condition has to check if all log files has been created and only then the reducer should run.

If there is any other file which gets created/appended on completion of all rat jobs, please let me know. We can put the condition there.

**Comment by chrismattmann** [comment]
I'll take a pass at this tonight

**Comment by karanjeets** [comment]
@chrismattmann @lewismc 
Finally, there is some progress on this. I have used Workflow condition with XmlRpcResourceManagerClient to check if any of the instances of Mime Partitioner and Rat Code Audit jobs are present in queue. If none is present, allow RatAggregator to run.

**Comment by chrismattmann** [comment]
awesome @karanjeets would love to see cc @lewismc

**Comment by karanjeets** [comment]
@chrismattmann @lewismc 
Done. Raised PR. [OODT PR Reference](https://github.com/apache/oodt/pull/35)

**Comment by chrismattmann** [comment]
awesome thank you @karanjeets  - see my comments to update

**Comment by chrismattmann** [comment]
ping @karanjeets

**Comment by karanjeets** [comment]
@chrismattmann 
Yes, this has been done. The updates are already in the PR.
