### ISSUE TITLE
Connect to OODT REST services from Proteus

### ISSUE THREAD

**Issue by junsuhle** [apache/drat#59]
We have a question regarding on Apache CFX and OODT REST 
Can we get the processing status of 'map' and 'reduce' by OODT REST? 
I thought map and reduce are not about OODT so cannot get process status for those two. 

Also, I looked at 'The OODT PCS Health Monitor service' https://cwiki.apache.org/confluence/display/OODT/OODT+REST+Services#OODTRESTServices-TheOODTPCSHealthMonitorservice

 and it's output includes 

"crawlerStatus"
"deamonStatus"
"ingestHealth"
"jobHealth"
and even
"LatestFiles" 

Question is. Isn't it pretty much all information for Crawling? 
(Assuming LatestFiles are the files that are ingested recently)

If so, we don't need any more REST request for crawling? 

Lastly, I also want to know what REST request related for indexing...
It would be very helpful.

**Comment by chrismattmann** [comment]
Hi @junsuhle I think what you're looking for is using XML-RPC and those interfaces. My suggestion would be to:
1. Write a JAX-RS service with Apache CXF (see e.g., http://github.com/chrismattmann/shangridocs/shangridocs-services/ for an example Maven project) that:
   a. Uses the XmlRpcWorkflowManagerClient in Apache OODT's cas-workflow API to connect to the Workflow Manager for DRAT and to get the status of the mappers and reduces (e.g., by calling getWorkflowInstancesByStatus and then sorting through the taskIds, etc.)
2. JobHealth from the PCS status gives the current tally and states of running jobs.
3. You can get LatestFiles from the PCS Health Monitor and I would suggest doing so.
4. We don't have a REST API to call the SolrIndexer, but we could develop one. @darth-pr can you help me write this interface? See here for docs: https://cwiki.apache.org/confluence/display/OODT/Using+the+SolrIndexer+to+dump+a+File+Manager+Catalog

**Comment by sfrancus** [comment]
@chrismattmann Currently when I try to get the RATLogs and RatAggregateLogs via the OODT File Manager REST API I get a NullPointerException when hitting this URL (http://localhost:8080/fmprod/dataset?typeID=urn:drat:RatLog)

org.apache.oodt.cas.filemgr.structs.exceptions.CatalogException: java.lang.Exception: java.lang.NullPointerException
    at org.apache.oodt.cas.filemgr.system.XmlRpcFileManagerClient.getFirstPage(XmlRpcFileManagerClient.java:489)
    at org.apache.oodt.cas.product.data.DatasetDeliveryServlet.doPut(DatasetDeliveryServlet.java:136)
    at org.apache.oodt.cas.product.data.DatasetDeliveryServlet.doGet(DatasetDeliveryServlet.java:84)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:210)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:542)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:870)
    at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
    at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:685)
    at java.lang.Thread.run(Thread.java:745)

Any thoughts? I'm trying to download the RAT(Aggregate)Logs to store as Json via the CXF Client API.

**Comment by chrismattmann** [comment]
I can confirm this is fixed in https://github.com/chrismattmann/drat/commit/65e5c4dc45cebc33b5d93ce39f2d63bfc47a8077
