### ISSUE TITLE
DRAT Mapper - Server returned HTTP response code: 500 for URL: http://localhost:8080/opsui/instances/PGE%20EXEC/1

### ISSUE THREAD

**Issue by karanjeets** [apache/drat#80]
While running mapper, DRAT breaks the current_pges loop and runs reduce job. This issue is intermittent and might related to the below mentioned error.

**DRAT Logs**

```
Waiting for the mapping and partitioning to finish.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Exception in thread "main" java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8080/opsui/instances/PGE%20EXEC/1
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
    at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    at org.apache.tika.io.TikaInputStream.get(TikaInputStream.java:395)
    at org.apache.tika.cli.TikaCLI.process(TikaCLI.java:416)
    at org.apache.tika.cli.TikaCLI.main(TikaCLI.java:112)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8080/opsui/instances/PGE%20EXEC/1
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
    at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2942)
    at java.net.URLConnection.getContentType(URLConnection.java:512)
    at org.apache.tika.io.TikaInputStream.get(TikaInputStream.java:380)
    ... 2 more

There are still MapReduce mappers running! It is reccomended you wait for them to finish, 
then try to run '$DRAT_HOME/bin/drat reduce' again later.
Stopping OODT...
/gpfs/flash/users/tg830544/final/drat/drat_master/deploy/bin /gpfs/flash/users/tg830544/final/logs
/gpfs/flash/users/tg830544/final/logs
```

**Tomcat Logs**

```
Nov 27, 2015 1:13:03 PM org.apache.jasper.compiler.JspRuntimeContext checkUnload
FINER: Checking JSPs for unload in context [/pcs], JSP count: 0 queue length: -1
STATUS IS PGE EXEC
org.apache.xmlrpc.XmlRpcException: java.lang.Exception: java.lang.NullPointerException
    at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeException(XmlRpcClientResponseProcessor.java:104)
    at org.apache.xmlrpc.XmlRpcClientResponseProcessor.decodeResponse(XmlRpcClientResponseProcessor.java:71)
    at org.apache.xmlrpc.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:73)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:194)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:185)
    at org.apache.xmlrpc.XmlRpcClient.execute(XmlRpcClient.java:178)
    at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManagerClient.paginateWorkflowInstances(XmlRpcWorkflowManagerClient.java:213)
    at org.apache.oodt.cas.webcomponents.workflow.WorkflowMgrConn.safeGetWorkflowInstPageByStatus(WorkflowMgrConn.java:146)
    at org.apache.oodt.cas.webcomponents.workflow.instance.WorkflowInstancesViewer.<init>(WorkflowInstancesViewer.java:89)
    at org.apache.oodt.pcs.opsui.WorkflowInstanceViewerPage.<init>(WorkflowInstanceViewerPage.java:43)
    at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:188)
    at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:89)
    at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:305)
    at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.getPage(BookmarkablePageRequestTarget.java:320)
    at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.processEvents(BookmarkablePageRequestTarget.java:234)
    at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
    at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1250)
    at org.apache.wicket.RequestCycle.step(RequestCycle.java:1329)
    at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1436)
    at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
    at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
    at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
ERROR - RequestCycle               - Can't instantiate page using constructor public org.apache.oodt.pcs.opsui.WorkflowInstanceViewerPage(org.apache.wicket.PageParameters) and argum
ent status = "PGE EXEC" pageNum = "1"
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor public org.apache.oodt.pcs.opsui.WorkflowInstanceViewerPage(org.apache.wicket.PageParameters) and 
argument status = "PGE EXEC" pageNum = "1"
    at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:212)
    at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:89)
    at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.newPage(BookmarkablePageRequestTarget.java:305)
    at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.getPage(BookmarkablePageRequestTarget.java:320)
    at org.apache.wicket.request.target.component.BookmarkablePageRequestTarget.processEvents(BookmarkablePageRequestTarget.java:234)
    at org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)
    at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1250)
    at org.apache.wicket.RequestCycle.step(RequestCycle.java:1329)
    at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1436)
    at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
    at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
    at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.apache.wicket.session.DefaultPageFactory.createPage(DefaultPageFactory.java:188)
    ... 28 more
Caused by: java.lang.NullPointerException
    at org.apache.oodt.cas.webcomponents.workflow.instance.WorkflowInstancesViewer.computeStartEndIdx(WorkflowInstancesViewer.java:205)
    at org.apache.oodt.cas.webcomponents.workflow.instance.WorkflowInstancesViewer.<init>(WorkflowInstancesViewer.java:92)
    at org.apache.oodt.pcs.opsui.WorkflowInstanceViewerPage.<init>(WorkflowInstanceViewerPage.java:43)
    ... 32 more
```

**Comment by chrismattmann** [comment]
looks like this happens before the page has loaded.. @karanjeets

**Comment by karanjeets** [comment]
@chrismattmann  Yes and it seems because of this error, tika got 500 error. I wonder why it shoots NullPointerException suddenly between the mapper process.

**Comment by lewismc** [comment]
How large is the input data that you are processing?

**Comment by karanjeets** [comment]
@lewismc Yes, the size of input data is quite large - [Apache ActiveMq Project](http://svn.apache.org/repos/asf/activemq)
Does it has to do with the input size ?

**Comment by lewismc** [comment]
@karanjeets 

>  Does it has to do with the input size ?

I've never seen this NPE before so I cannot comment however I would state that if it is NPE is is most likely not coming from input data given the fact that it is only one source codebase you are analyzing. 

Can you reproduce?

**Comment by karanjeets** [comment]
@lewismc I am pretty sure that this can be reproduced. I will let you know soon.
