### ISSUE TITLE
Unable to serialize class: org.apache.oodt.cas.workflow.structs.WorkflowInstance

### ISSUE THREAD

**Issue by karanjeets** [apache/drat#81]
Is there any significance of this error ? This seems to be appearing at regular intervals in **tomcat logs**

```
STATUS IS PGE EXEC
ERROR - Objects                    - Error serializing object class org.apache.oodt.pcs.opsui.WorkflowInstanceViewerPage [object=[Page class = org.apache.oodt.pcs.opsui.WorkflowInst
anceViewerPage, id = 0, version = 0]]
org.apache.wicket.util.io.SerializableChecker$WicketNotSerializableException: Unable to serialize class: org.apache.oodt.cas.workflow.structs.WorkflowInstance
Field hierarchy is:
  0 [class=org.apache.oodt.pcs.opsui.WorkflowInstanceViewerPage, path=0]
    private java.lang.Object org.apache.wicket.MarkupContainer.children [class=[Ljava.lang.Object;]
      private org.apache.wicket.markup.html.link.PopupSettings org.apache.wicket.markup.html.link.Link.popupSettings[9] [class=org.apache.oodt.cas.webcomponents.workflow.instance.Wo
rkflowInstancesViewer, path=0:instance_viewer]
        private java.lang.Object org.apache.wicket.MarkupContainer.children [class=[Ljava.lang.Object;]
          java.lang.Object org.apache.wicket.Component.data[4] [class=org.apache.oodt.cas.webcomponents.workflow.instance.WorkflowInstancesViewer$2, path=0:instance_viewer:workflow_
insts]
            java.lang.Object org.apache.wicket.Component.data [class=org.apache.wicket.model.util.ListModel]
              private java.lang.Object org.apache.wicket.model.util.GenericBaseModel.object [class=java.util.Vector]
                private java.lang.Object org.apache.wicket.model.util.GenericBaseModel.object[write:1] [class=[Ljava.lang.Object;]
                  private java.lang.Object org.apache.wicket.model.util.GenericBaseModel.object[write:1][0] [class=org.apache.oodt.cas.workflow.structs.WorkflowInstance] <----- fiel
d that is not serializable
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:386)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:432)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.access$500(SerializableChecker.java:64)
    at org.apache.wicket.util.io.SerializableChecker$1InterceptingObjectOutputStream.replaceObject(SerializableChecker.java:535)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144)
    at java.io.ObjectOutputStream.access$300(ObjectOutputStream.java:162)
    at java.io.ObjectOutputStream$PutFieldImpl.writeFields(ObjectOutputStream.java:1707)
    at java.io.ObjectOutputStream.writeFields(ObjectOutputStream.java:482)
    at java.util.Vector.writeObject(Vector.java:1077)
    at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:542)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.checkFields(SerializableChecker.java:656)
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:579)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.checkFields(SerializableChecker.java:656)
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:579)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:432)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.checkFields(SerializableChecker.java:656)
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:579)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:432)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.checkFields(SerializableChecker.java:656)
    at org.apache.wicket.util.io.SerializableChecker.internalCheck(SerializableChecker.java:579)
    at org.apache.wicket.util.io.SerializableChecker.check(SerializableChecker.java:365)
    at org.apache.wicket.util.io.SerializableChecker.writeObjectOverride(SerializableChecker.java:725)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
    at org.apache.wicket.util.io.IObjectStreamFactory$DefaultObjectStreamFactory$2.writeObjectOverride(IObjectStreamFactory.java:129)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
    at org.apache.wicket.util.lang.Objects.objectToByteArray(Objects.java:1124)
    at org.apache.wicket.protocol.http.pagestore.AbstractPageStore.serializePage(AbstractPageStore.java:203)
    at org.apache.wicket.protocol.http.pagestore.DiskPageStore.storePage(DiskPageStore.java:840)
    at org.apache.wicket.protocol.http.SecondLevelCacheSessionStore$SecondLevelCachePageMap.put(SecondLevelCacheSessionStore.java:332)
    at org.apache.wicket.Session.requestDetached(Session.java:1435)
    at org.apache.wicket.RequestCycle.detach(RequestCycle.java:1176)
    at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1462)
    at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)
    at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)
    at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: org.apache.oodt.cas.workflow.structs.WorkflowInstance
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
    at java.io.ObjectOutputStream.access$300(ObjectOutputStream.java:162)
    at java.io.ObjectOutputStream$PutFieldImpl.writeFields(ObjectOutputStream.java:1707)
    at java.io.ObjectOutputStream.writeFields(ObjectOutputStream.java:482)
    at java.util.Vector.writeObject(Vector.java:1077)
    at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
    at org.apache.wicket.Component.writeObject(Component.java:4700)
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at org.apache.wicket.util.io.IObjectStreamFactory$DefaultObjectStreamFactory$2.writeObjectOverride(IObjectStreamFactory.java:121)
    ... 28 more
```

**Comment by chrismattmann** [comment]
it's a wicket error, having to do with those objects not implementing Serializable. If you can fix (upstream in OODT in the opsui package) that would be awesome!

**Comment by chrismattmann** [comment]
@karanjeets

**Comment by karanjeets** [comment]
@chrismattmann Yes, I can look into this after exams. Do you think this produces #80 or affects any part of the DRAT's workflow ?

**Comment by chrismattmann** [comment]
yeah possibly..

**Comment by lewismc** [comment]
This is an inherent problem with all org.aapache.oodt._._.structs.\* package classes in OODT. The key data structures do not implement Serializable so we have some work to do.

**Comment by chrismattmann** [comment]
agreed @lewismc . @karanjeets can you file an issue in OODT to track this?

**Comment by karanjeets** [comment]
@chrismattmann done. Issue https://issues.apache.org/jira/browse/OODT-920 raised.

**Comment by chrismattmann** [comment]
no time to fix this. Annoyance, but not blocker.
